Hilt/Hub/HiltHub/Controllers/aulController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using MvcContrib.UI.Grid;
using MvcContrib.Pagination;
using MvcContrib.Sorting; 
using HiltHub.Models;

namespace HiltHub.Controllers
{
    public partial class AulController : Controller
    {
        //
        // GET: /aul/

        public virtual ActionResult Clear()
        {
            return RedirectToAction("Index");
        }

        public virtual ActionResult Index(int? page, 
                                    GridSortOptions gridSortOptions, 
                                    string niin, 
                                    string description,
                                    string cage,
									int? shipId,
                                    int? catalogGroupId)
        {
            ViewBag.section = "aul";
            int? pageSize = null;
            if (Request.Cookies["pageSize"] != null)
                pageSize = Convert.ToInt16(Request.Cookies["pageSize"].Value);

            var dc = new hubDataClassesDataContext();
            if (string.IsNullOrWhiteSpace(gridSortOptions.Column)) { gridSortOptions.Column = "description"; }
            var model = new AulListContainerViewModel();

            IQueryable<v_AUL_HullType_Detail> aulList = dc.v_AUL_HullType_Details.Where(x => x.niin != "UNKNOWN");
            
            if (!String.IsNullOrEmpty(niin))
                aulList = aulList.Where(x => x.niin.Contains(niin));
/*
            if (shipId >= 0)
                aulList = aulList.Where(x => x..Equals(shipId));
*/
            if (!String.IsNullOrEmpty(description))
                aulList = aulList.Where(x => x.description.Contains(description));

            if (catalogGroupId >= 0)
                aulList = aulList.Where(x => x.catalog_group_id == catalogGroupId);

            model.AulPagedList = aulList
                                     .OrderBy(gridSortOptions.Column, gridSortOptions.Direction)
                                    .AsPagination(page ?? 1, pageSize ?? 10);
            model.GridSortOptions = gridSortOptions;
            model.AulFilterViewModel = new AulFilterViewModel
                                           {
                                               NIIN = niin,
                                               Description = description,
                                               CatalogGroupId = catalogGroupId ?? -1,
                                               CatalogGroups = new SelectList(dc.catalog_groups.AsEnumerable(), "catalog_group_id", "group_name"),
                                               ShipId = shipId ?? -1,
                                               Ships = new SelectList(dc.ships.AsEnumerable(), "ship_id", "name"),
                                           };
            return View(model);
        }


        //
        // GET: /aul/Details/5
        public virtual ActionResult Details(string id)
        {
            var dc = new hubDataClassesDataContext();
            v_AUL_HullType_Detail model = dc.v_AUL_HullType_Details.First(x => x.niin == id);
            return View(model);
        }
    }
}

Hilt/Hub/HiltHub/Controllers/msdsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Linq;
using System.Data.OleDb;
using System.Linq;
using System.Reflection;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.IO;
using HiltHub.Models;
using MvcContrib.Pagination;
using MvcContrib.Sorting;
using MvcContrib.UI.Grid;
using ExtensionMethods;

namespace HiltHub.Controllers
{
    public partial class MsdsController : Controller
    {
        //
        // GET: /msds/

        public virtual ActionResult Clear()
        {
            return RedirectToAction("Index");
        }

        private static void ExplodeContractorTable()
        {
            var dc = new hubDataClassesDataContext();
            IEnumerable<msds_contractor_info> csContractorList =
                dc.msds_contractor_infos.OrderBy("contractor_id", SortDirection.Ascending).Where(x => x.CT_CAGE.Contains(",")).AsEnumerable();
            if (csContractorList == null) return;
            foreach (msds_contractor_info csContractor in csContractorList)
            {
                if (csContractor.CT_CAGE == null
                    || csContractor.CT_CITY == null
                    || csContractor.CT_COMPANY_NAME == null
                    || csContractor.CT_COUNTRY == null
                    //|| csContractor.CT_NUMBER == null
                    || csContractor.CT_PHONE == null
                    || csContractor.CT_PO_BOX == null
                    //|| csContractor.PURCHASE_ORDER_NO == null
                    || csContractor.CT_STATE == null) continue;
                string[] ct_cages = csContractor.CT_CAGE.Split(',');
                if (ct_cages.Count() < 2) continue;
                string[] ct_cities = csContractor.CT_CITY.Split(',');
                string[] ct_company_names = csContractor.CT_COMPANY_NAME.Split(',');
                string[] ct_countries = csContractor.CT_COUNTRY.Split(',');
                //string[] ct_numbers = csContractor.CT_NUMBER.Split(',');
                string[] ct_phones = csContractor.CT_PHONE.Split(',');
                string[] ct_po_boxes = csContractor.CT_PO_BOX.Split(',');
                //string[] purchase_order_nos = csContractor.PURCHASE_ORDER_NO.Split(',');
                string[] ct_states = csContractor.CT_STATE.Split(',');
                for (int i = 0; i < ct_cages.Count(); i++)
                {
                    msds_contractor_info splitContractorI =
                        new msds_contractor_info
                        {
                            CT_CAGE = ct_cages[i],
                            CT_CITY = ct_cities[i],
                            CT_COMPANY_NAME = ct_company_names[i],
                            CT_COUNTRY = ct_countries[i],
                            //CT_NUMBER = ct_numbers[i],
                            CT_PHONE = ct_phones[i],
                            CT_PO_BOX = ct_po_boxes[i],
                            CT_STATE = ct_states[i],
                            //PURCHASE_ORDER_NO = purchase_order_nos[i],
                            contractor_id = csContractor.contractor_id,
                            //msds_id = csContractor.msds_id
                        };
                    dc.msds_contractor_infos.InsertOnSubmit(splitContractorI);
                    dc.SubmitChanges();
                }
                dc.msds_contractor_infos.DeleteOnSubmit(csContractor);
                dc.SubmitChanges();
            }
        }
        
        private static void ExplodeIngredientsTable()
        {
            var dc = new hubDataClassesDataContext();
            
            IEnumerable<msds_ingredient> csIngredientsList =
                dc.msds_ingredients.OrderBy("ingredients_id", SortDirection.Ascending).Where(x => x.CAS.Contains(",")).AsEnumerable();
            if (csIngredientsList == null) return;
            foreach (msds_ingredient csIngredient in csIngredientsList)
            {
                if (csIngredient.ACGIH_STEL == null
                    || csIngredient.ACGIH_TLV == null
                    || csIngredient.CAS == null
                    || csIngredient.CHEM_MFG_COMP_NAME == null
                    || csIngredient.DOT_REPORT_QTY == null
                    || csIngredient.EPA_REPORT_QTY == null
                    || csIngredient.INGREDIENT_NAME == null
                    || csIngredient.ODS_IND == null
                    || csIngredient.OSHA_PEL == null
                    || csIngredient.OSHA_STEL == null
                    || csIngredient.OTHER_REC_LIMITS == null
                    || csIngredient.PRCNT == null
                    || csIngredient.PRCNT_VOL_VALUE == null
                    || csIngredient.PRCNT_VOL_WEIGHT == null
                    || csIngredient.RTECS_CODE == null
                    || csIngredient.RTECS_NUM == null) continue;
                
                string[] acgih_tlvs = csIngredient.ACGIH_TLV.Split(',');
                if (acgih_tlvs.Count() < 2) continue;
                string[] acgih_stels = csIngredient.ACGIH_STEL.Split(',');
                string[] cass = csIngredient.CAS.Split(',');
                string[] chem_mfg_comp_names = csIngredient.CHEM_MFG_COMP_NAME.Split(',');
                string[] dot_report_qtys = csIngredient.DOT_REPORT_QTY.Split(',');
                string[] epa_report_qtys = csIngredient.EPA_REPORT_QTY.Split(',');
                string[] ingredient_names = csIngredient.INGREDIENT_NAME.Split(',');
                string[] ods_inds = csIngredient.ODS_IND.Split(',');
                string[] osha_pels = csIngredient.OSHA_PEL.Split(',');
                string[] osha_stels = csIngredient.OSHA_STEL.Split(',');
                string[] other_rec_limits = csIngredient.OTHER_REC_LIMITS.Split(',');
                string[] prcnts = csIngredient.PRCNT.Split(',');
                string[] prcnt_vol_values = csIngredient.PRCNT_VOL_VALUE.Split(',');
                string[] prcnt_vol_weights = csIngredient.PRCNT_VOL_WEIGHT.Split(',');
                string[] rtecs_codes = csIngredient.RTECS_CODE.Split(',');
                string[] rtecs_nums = csIngredient.RTECS_NUM.Split(',');
                try
                {
                    for (int i = 0; i < acgih_tlvs.Count(); i++)
                    {
                        msds_ingredient splitIngredientI =
                            new msds_ingredient
                                {
                                    ACGIH_STEL = acgih_stels[i],
                                    ACGIH_TLV = acgih_tlvs[i],
                                    CAS = cass[i],
                                    CHEM_MFG_COMP_NAME = chem_mfg_comp_names[i],
                                    DOT_REPORT_QTY = dot_report_qtys[i],
                                    EPA_REPORT_QTY = epa_report_qtys[i],
                                    INGREDIENT_NAME = ingredient_names[i],
                                    ODS_IND = ods_inds[i],
                                    OSHA_PEL = osha_pels[i],
                                    OSHA_STEL = osha_stels[i],
                                    OTHER_REC_LIMITS = other_rec_limits[i],
                                    PRCNT = prcnts[i],
                                    PRCNT_VOL_VALUE = prcnt_vol_values[i],
                                    PRCNT_VOL_WEIGHT = prcnt_vol_weights[i],
                                    RTECS_CODE = rtecs_codes[i],
                                    RTECS_NUM = rtecs_nums[i],
                                    msds_id = csIngredient.msds_id,
                                    ingredients_id = csIngredient.ingredients_id
                                };
                        dc.msds_ingredients.InsertOnSubmit(splitIngredientI);
                        dc.SubmitChanges();
                    }
                    dc.msds_ingredients.DeleteOnSubmit(csIngredient);
                    dc.SubmitChanges();
                }
                catch (Exception)
                {
                }
            }
        }

        // Some of the Contractor and Ingredients data comes to us in comma-separated records.
        // We have a much easier time handling these if they're split into individual records.
        public static void ExplodeContractorAndIngredientsTables()
        {
            ExplodeIngredientsTable();
            ExplodeContractorTable();
        }

        [HttpGet]
        public virtual JsonResult GetExportList(string niin,
                                  string msdsSerNo,
                                  int? shipId,
                                  int? hullTypeId,
                                  string product,
                                  string manufacturer)
        {
            List<string> msdsList = GetMsdsList(niin, msdsSerNo, shipId, hullTypeId, product, manufacturer).Select(x => x.Master_MSDSSERNO).ToList();
            return Json(msdsList, JsonRequestBehavior.AllowGet);
        }

        public virtual void ExportSingle(string msdsSerNo, int? hullTypeId)
        {
            Export(null, msdsSerNo, null, hullTypeId, null, null);
        }

        public virtual ActionResult Export(string niin,
                                  string msdsSerNo,
                                  int? shipId,
                                  int? hullTypeId,
                                  string product,
                                  string manufacturer)
        {
            IEnumerable<v_MSDS_HullType_Detail> msdsList = GetMsdsList(niin, msdsSerNo, shipId, hullTypeId, product, manufacturer).Take(10);
            var dc = new hubDataClassesDataContext();
            string DocumentsSource = Configuration.HILT_HUB_DataFolder + @"\MSDS_Docs";

            // init folders, etc
            string FolderName = "All";
            if (hullTypeId > -1)
            {
                FolderName = dc.hull_types.First(x => x.hull_type_id == hullTypeId).hull_description;
            }

Hilt/Hub/HiltHub/Controllers/msslController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using MvcContrib.UI.Grid;
using MvcContrib.Pagination;
using MvcContrib.Sorting;
using HiltHub.Models;
using ExtensionMethods;

namespace HiltHub.Controllers
{
    public partial class MsslController : Controller
    {
        public virtual ActionResult Clear()
        {
            return RedirectToAction("Index");
        }

        public virtual ActionResult Index(int? page, 
				GridSortOptions gridSortOptions, 
				string niin,
                string product,
                string shelfLife,
				int? shipId)
        {
            ViewBag.section = "mssl";
            int? pageSize = null;
            if (Request.Cookies["pageSize"] != null)
                pageSize = Convert.ToInt16(Request.Cookies["pageSize"].Value);

            var dc = new hubDataClassesDataContext();
            var model = new MsslListContainerViewModel();

            // get list
            IQueryable<v_MSSL_Inventory_Detail> msslList = dc.v_MSSL_Inventory_Details;

            // filter
            if (!String.IsNullOrEmpty(niin))
                msslList = msslList.Where(x => x.NIIN.Contains(niin));

            if (!String.IsNullOrEmpty(product))
                msslList = msslList.Where(x => x.Nomenclature.Contains(product));

            if (!String.IsNullOrEmpty(shelfLife))
                msslList = msslList.Where(x => x.Shelf_Life_Code.Equals(shelfLife));

            if (shipId >= 0)
                msslList = msslList.Where(x => x.ship_id.Equals(shipId));

            msslList = msslList.GroupBy(x=>x.NIIN).Select(x=>x.First()).OrderBy(e=>e.NIIN);

            model.MsslPagedList = msslList
                                      .OrderBy(gridSortOptions.Column, gridSortOptions.Direction)
                                    .AsPagination(page ?? 1, pageSize ?? 10);
            model.GridSortOptions = gridSortOptions;

            IOrderedQueryable<v_MSSL_Inventory_Detail> shelfLives = dc.v_MSSL_Inventory_Details.GroupBy(x=>x.Shelf_Life_Description)
                                .Select(x=>x.First()).OrderBy(e => e.Shelf_Life_Description);
            SelectList shelfLifeList = 
                new SelectList(shelfLives, "Shelf_Life_Code", "Shelf_Life_Description");

            model.MsslFilterViewModel = new MsslFilterViewModel
                                           {
                                               NIIN = niin,
                                               Product = product,
                                               ShelfLife = shelfLifeList,
                                               ShipId = shipId ?? -1,
                                               Ships = new SelectList(dc.ships.AsEnumerable(), "ship_id", "name"),
                                           };            
            return View(model);
        }

        //
        // GET: /mssl/Details/5

        public virtual ActionResult Details(string id)
        {
            var dc = new hubDataClassesDataContext();
            v_MSSL_Inventory_Detail model = dc.v_MSSL_Inventory_Details.First(x => x.NIIN == id);
            return View(model);
        }
    }
}

Hilt/Hub/HiltHub/Views/Shared/DetailsHeader.cshtml
@model HiltHub.Models.DetailsHeaderData
<script>
    $(function () {
        $('#btnSave').click(function () {
            $('form').submit();
        });
    });
</script>
<style>
    .DetailsTitle {
        font-family: Impact, Charcoal, sans-serif;
        font-size: 26px;
        margin-top: 5px;
        line-height: 26px;
    }
    
    .DetailsSubTitle {
        font-size: 12px;
        font-family: verdana, sans-serif;
        margin-bottom: 30px;
    }
</style>

<div id="DetailsHeader" style="float: left; width: 350px;">
    <div class="DetailsTitle">@Model.Title</div> 	
    <div class="DetailsSubTitle">@Model.SubTitle</div>
</div>

<div class="btn-group" style="margin-bottom: 10px; float: right; margin-right: 12px">
@{
    Html.RenderPartial("_backToList", null);
    if (Model.ShowSave)  {
        <div class="btn" onclick="$('form').submit()"><i class="icon-save"></i> Save</div>
    }
}
</div>

<br style="clear: both"/>

Hilt/Hub/HiltHub/Views/Shared/PagerGroup.cshtml
@using MvcContrib.UI.Pager
@model MvcContrib.Pagination.IPagination
<div id="paginationContainer">
@{ Html.RenderPartial("PagerMoreLess", Model); }
@Html.Pager(Model).Format("{0} - {1} of {2}")
</div>

Hilt/Hub/HiltHub/Views/Shared/PagerMoreLess.cshtml
<span id="btnGroupMoreLess" class="btn-group">
<a id="pagerMore" class="btn"><i class="icon-plus"></i> more</a>
<a class="btn moreLessSeparator"><i class="icon-th-list"></i></a>
<a id="pagerLess" class="btn"><i class="icon-minus"></i> less</a>
</span>

Hilt/Hub/HiltHub/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>HILT Hub - @ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="@Url.Content("~/Content/bootstrap/css/bootstrap.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/font-awesome/css/font-awesome.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet/less" type="text/css" >
    <script src="@Url.Content("~/Scripts/less-1.3.0.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-1.7.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.cookie.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/ligature.js")" type="text/javascript"></script>
	<script type="text/javascript">
        function setFocus()
        {
            // Set focus to the first input or select control on the page
            var inputs = $('input[type="text"]:visible, select:visible, textarea:visible');

	        if (inputs.length > 0) {
               inputs[0].focus();
	        }
	        else // no input controls?  set focus to the first link.
	        { 
	            var links = $('a');
	            if (links.length > 0) {
	                links[0].focus();
	            }
	        }
        }

	    $(function () {
            setFocus();

            // load background image
            $('body').css('background-image', "url( '@Url.Content("~/Content/noise.png")' )");

            // nav select indicator \/
            $('body#aul li#aulNav a, body#msds li#msdsNav a, body#mssl li#msslNav a, body#ship li#shipNav a, body#import li#importNav a, body#dashboard li#dashboardNav a').css(
                'background-image', "url( '@Url.Content("~/Content/dot.png")' )");

    	    // Opens links of class "new-window" in a new window
	        $('a.new-window').click(function () {
	            window.open(this.href);
	            return false;
	        });

            // Turn on the "please wait" sign for long operations
            $('.selectPleaseWait').change(showPleaseWait);
	        $('input[type=submit], .pleaseWait').click(showPleaseWait);

            // change icons to white on hover
            $('.btn-group > div').hover(
                function(){
                    $(this).find('i').addClass("icon-white");
                },
                function(){
                    $(this).find('i').removeClass("icon-white");
                });
	    });
        
        function showPleaseWait()
        {
            $('#pleaseWait').modal({'backdrop': 'static'});
        }

        function hidePleaseWait()
        {
            $('#pleaseWait').modal('hide');
        }

        function showProgressBox()
        {
            $('#progressBox').modal({'backdrop': 'static'});
        }

        function hideProgressBox()
        {
            $('#progressBox').modal('hide');
        }

        String.prototype.trim = function() {
            return replace( /^\s+|\s+$/g , "");
        };
	</script>
</head>
<body id="@ViewBag.section">
	<div id="pleaseWait" class="modal hide">
        <div class="modal-body">
			Please wait 
			<img id="spinner" src="@Url.Content("~/Content/spin.gif")" alt="spin"/>
        </div>
	</div>

    <div id="progressBox" class="modal hide">
        <div class="modal-body">
            <div class="progress progress-striped active">
                <div id="progressBar" class="bar"></div>
            </div>
            Exporting: 
            <span id="currentMsds">
            </span>
        </div>
    </div>
    
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div style="width: 900px; height: 38px; margin-left: auto; margin-right: auto;">
          <div>
              <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </a>
              <div style="float: left; height: 40px; margin-right: 40px">
                  <a class="brand" href="@Url.Content("~")">HILT hub</a>
                  <div id="version">version @HiltHub.MvcApplication.version</div>
              </div>
              <div class="btn-group pull-right" style="padding: 0px; margin-top: 5px">
                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#" style="width: 150px; margin-right: 0px">
                  <i class="icon-user"></i> @User.Identity.Name
                  <!--span class="caret"></span-->
                </a>
                <ul class="dropdown-menu">
                  <li><a href="#">Profile</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Sign Out</a></li>
                </ul>
              </div>
              <div class="nav-collapse">
                <ul class="nav">
				    <li id="dashboardNav">@Html.ActionLink("Dashboard", "Index", "dashboard")</li>
				    <li id="aulNav">@Html.ActionLink("AUL", "Index", "Aul")</li>
				    <li id="msdsNav">@Html.ActionLink("MSDS", "Index", "Msds")</li>
				    <li id="msslNav">@Html.ActionLink("MSSL", "Index", "Mssl")</li>
				    <li id="shipNav">@Html.ActionLink("Ship", "Index", "Ship")</li>
                    <li id="importNav">@Html.ActionLink("Import", "Index", "FileImport")</li>
                </ul>
              </div><!--/.nav-collapse -->
          </div>
        </div>
      </div>
    </div>

    <div class="hero-unit shadow">
        @RenderBody()
    </div>

    <script type="text/javascript" src="@Url.Content("~/Content/bootstrap/js/bootstrap.js")"></script>
</body>
</html>

Hilt/Hub/HiltHub/Views/Shared/_Popup.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap/css/bootstrap.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.2.js")" type="text/javascript"></script>
	<script type="text/javascript">
		// Enable auto-postback for drop-downs, radio buttons, and checkboxes
		$(document).ready(function() {
			$("select:[autopostback='True']").change(
				function() {
					$(this).closest("form").submit();
				});
		});
	</script>
</head>
<body style="width: 810px">
    <div style="margin: 5px;">
		<div id="main" style="width: 800px">
			@RenderBody()        
		</div>
	</div>
</body>
</html>

Hilt/Hub/HiltHub/Views/Shared/_backToList.cshtml
<a href="@Url.Content("~/" + this.ViewContext.Controller.ValueProvider.GetValue("controller").RawValue.ToString())" class="btn backToList"><i class="icon-arrow-left"></i> Back to List</a>

Hilt/Hub/HiltHub/Views/Shared/_tbdMessage.cshtml
<div class="tbdMessage">
@HiltHub.MvcApplication.TBDMessage
</div>